# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_theta <- function(data, mu, ax, bx, tol) {
    .Call(`_bayescount_find_theta`, data, mu, ax, bx, tol)
}

pbnb <- function(q, k, alpha, beta, lower, inclusive) {
    .Call(`_bayescount_pbnb`, q, k, alpha, beta, lower, inclusive)
}

estimate_k_useless <- function(mean_1, var_1, mean_2, var_2, cov_12, paired) {
    .Call(`_bayescount_estimate_k_useless`, mean_1, var_1, mean_2, var_2, cov_12, paired)
}

estimate_k_experiment <- function(mean_1, var_1, mean_2, var_2, cov_12, paired) {
    .Call(`_bayescount_estimate_k_experiment`, mean_1, var_1, mean_2, var_2, cov_12, paired)
}

estimate_k <- function(mean_1, var_1, mean_2, var_2, cov_12, paired) {
    .Call(`_bayescount_estimate_k`, mean_1, var_1, mean_2, var_2, cov_12, paired)
}

estimate_k_ml <- function(data_1, mean_1, var_1, data_2, mean_2, var_2, cov_12, paired) {
    .Call(`_bayescount_estimate_k_ml`, data_1, mean_1, var_1, data_2, mean_2, var_2, cov_12, paired)
}

get_type_ci <- function(eff, lci, uci, ta, ti) {
    .Call(`_bayescount_get_type_ci`, eff, lci, uci, ta, ti)
}

get_type_pv <- function(eff, p1, p2, tail, ta, ti) {
    .Call(`_bayescount_get_type_pv`, eff, p1, p2, tail, ta, ti)
}

methodcomp <- function(sum1, N1, K1_p, K1_u, mu1, var1, sum2, N2, K2_p, K2_u, mu2, var2, cov12, mean_ratio, H0_1, H0_2, conjugate_priors, delta, beta_iters, approx, tail, dobson_cl, dobson_priors) {
    .Call(`_bayescount_methodcomp`, sum1, N1, K1_p, K1_u, mu1, var1, sum2, N2, K2_p, K2_u, mu2, var2, cov12, mean_ratio, H0_1, H0_2, conjugate_priors, delta, beta_iters, approx, tail, dobson_cl, dobson_priors)
}

fecrt_sim_unpaired <- function(iters, red, N_tx, N_ctl, mu, k_tx, k_ctl, thresholds, conjugate_priors, delta, beta_iters, approx, tail, useml) {
    .Call(`_bayescount_fecrt_sim_unpaired`, iters, red, N_tx, N_ctl, mu, k_tx, k_ctl, thresholds, conjugate_priors, delta, beta_iters, approx, tail, useml)
}

fecrt_sim_paired <- function(iters, red, N, mu, k_pre, k_post, k_c, thresholds, conjugate_priors, delta, beta_iters, approx, tail, useml, dobson_cl, dobson_priors) {
    .Call(`_bayescount_fecrt_sim_paired`, iters, red, N, mu, k_pre, k_post, k_c, thresholds, conjugate_priors, delta, beta_iters, approx, tail, useml, dobson_cl, dobson_priors)
}

